[package]
name = "literate-snake"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"
lto = "thin"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = "0.7"
rand = "0.7.3"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
